### ISSUE TITLE
Fix issues like https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-tutorial-lab-testing/1233716437973995520

### ISSUE THREAD

**Issue by iranzo** [kubevirt/kubevirt-tutorial#114]
Get issues like https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-tutorial-lab-testing/1233716437973995520 on current infra

**Comment by dhiller** [comment]
Still [failing](https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-tutorial-lab-testing/1271405244500152320/build-log.txt?Expires=1592299344&GoogleAccessId=prow-46%40kubevirt-240711.iam.gserviceaccount.com&Signature=WHV0VD5TC3efOOdhFgj7l67Uq6bv72Dqe7ZFeNlGJG2UdtegeZxOoMOLOULYFv8HXtSmC%2B88esl5rZjjooxsG6R8ZyIkc4oJgHhevzNWPsAxcaCamAP41yzHPZvtK30p4gIQ08sbH5bFxPyt3xcHI8Wxm25fY8CGOvVl0HNmlmqrFjRhFdzmEzdn522Qbyr%2FxgiNuemivlZy44mY96IyohwalZkzU%2B2sz5JJwkGewCUimx9XF554g4ZD8meCb0eyOW6rgCfi253oQnW3wxlSo32wzOrNFfQzGj7v0JTCr2u96l1rpZGQzQ5sh8I%2BS1%2BvCNVpWKCFF4UQ%2BccH0QbpWw%3D%3D).

See prow here: https://prow.apps.ovirt.org/?job=periodic-kubevirt-tutorial-lab-testing&state=failure

**Comment by dhiller** [comment]
@iranzo @jparrill is anyone working on this?

**Comment by iranzo** [comment]
@dhiller probably better to tag people in Community team like  @codificat @mazzystr

**Comment by rmohr** [comment]
ping?

**Comment by rmohr** [comment]
/assign @codificat 

ping?

**Comment by codificat** [comment]
apologies for the delay, I'll get to this as soon as possible

**Comment by codificat** [comment]
I'm sorry I didn't update this earlier - I just noticed it auto-close.

Just wanted to mention that this job is now passing. e.g [this is today's execution](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-tutorial-lab-testing/1330838347483975680)
