### ISSUE TITLE
presubmit-lab-testing job broke

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt-tutorial#119]
kubevirt-tutorial-presubmit-lab-testing-k8s-1.13.3 is statically set to k8s 1.13.3.  

We're now getting job failures.  See failed #118 pull/118 and see [link](https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt-tutorial/118/kubevirt-tutorial-presubmit-lab-testing-k8s-1.13.3/1384421383693406208)

**Comment by ansijain** [comment]
Fixed in https://github.com/kubevirt/kubevirt-tutorial/pull/120
