### ISSUE TITLE
Fedora name should be changed 

### ISSUE THREAD

**Issue by DirectedSoul1** [kubevirt/kubevirt-tutorial#86]
In lab 8, when we talk about **Confirm connectivity** section 
`Through cloudinit, we also configured fedora-multus-1 vm to have ip 11.0.0.5 and fedora-multus-1 vm to have ip 11.0.0.6 so try to ping or ssh between them`

Here, vm name with IP `11.0.0.6` should be `fedora-multus-2` instead of `fedora-multus-1`

**Comment by iranzo** [comment]
Already corrected in latest version: https://github.com/kubevirt/kubevirt-tutorial/blob/master/labs/lab008/lab008.md
