### ISSUE TITLE
Lab 9 - Missing Fedora OS from drop down

### ISSUE THREAD

**Issue by DirectedSoul1** [kubevirt/kubevirt-tutorial#87]
In lab 9, a process to create VM's from a GUI, the section says to select an OS as `fedora29` but we dont have this in the drop down.

Under **Using the kubevirt web ui
              Create a Virtual Machine**
In the Basic Settings configure with the following

Name: vm3
Namespace: myproject
Provision Source: Container
Container Image: docker.io/kubevirt/cirros-registry-disk-demo:latest
Operating System: **fedora29** - No OS with **fedora** available.
`Memory: 1` - **No option to select Memory**
`CPUs: 1` - **No option to select CPU count**
Workload Profile: generic

**Comment by iranzo** [comment]
OCP Labs on website ( kubevirt.io/labs/ocp/) have been deprecated and moved to new structure for automated testing and validation. 

Closing, reopen if still happening
