### ISSUE TITLE
Lab 2, different client and server versions

### ISSUE THREAD

**Issue by slintes** [kubevirt/kubevirt-tutorial#97]
It's not critical, but not very nice: kubectl is 1.15.0, server 1.14.3

```
[kubevirt@kubevirtlab-2 ~]$ k version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by slintes** [comment]
seems it was just coincidence while 1.15 was in process of being released. On a new VM both are 1.15 now. Not sure if it would make sense to use a fixed version and not just latest, in order to prevent surprises?

**Comment by ptrnull** [comment]
@slintes we can add a warning to ensure that the user takes care of that when installing kubectl to have it compatible like we do in: https://travis-ci.org/kubevirt/kubevirt.github.io/builds/548026991#L543
Something like:
(*): Ensure that kubectl version complies with the supported release skew (The version of kubectl should be close to Kubernetes server version).
What do you think?

**Comment by slintes** [comment]
The user doesn't install kubectl, it was already installed IIRC. So I am not sure if such a warning would be more confusing than helping. 
My idea was to use a fixed k8s version in [0] for kubeadm, kubelet and kubectl, which will prevent a version mismatch while k8s releases a new version, and one package is newer than the other (I think that happened when I reported this). But that would mean that it needs manual updates, not sure if you want that. And, last but not least, I think this was just a seldom coincidence, not sure if you want to do anything about it at all. I would be fine with just closing this :)

[0] https://github.com/kubevirt/kubevirt-tutorial/blob/master/administrator/ansible/roles/common/tasks/centos.yml#L78

**Comment by iranzo** [comment]
@slintes : We had that discussion precisely on the minikube as the problem was the same, available command was not in the supported matrix for kubernetes and failed.

So we went by putting that warning 'instead' as if not, it would have meant to reupdate many references on each release once validated

**Comment by ptrnull** [comment]
/close
As @slintes said: 
> I think this was just a seldom coincidence, not sure if you want to do anything about it at all. I would be fine with just closing this :)
I also agree on that.
